
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: tfm-springboot-test
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: mysql:8
        env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: password
        volumeMounts:
          - name: mysqldb-volume 
            mountPath: "/var/lib/mysql"            
      volumes:
        - name: mysqldb-volume
          persistentVolumeClaim:
            claimName: pvc-mysqldb
                
---

apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: tfm-springboot-test
spec:
  ports:
  - port: 3306
  selector:
    app: mysqldb
  type: ClusterIP
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysqldb
  namespace: tfm-springboot-test
spec:
  storageClassName: mysqldb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  
      
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysqldb
  namespace: tfm-springboot-test
spec:
  storageClassName: mysqldb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db/mysql"
