---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: tfm-springboot
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.tfm-springboot: semver:~1
spec:
  selector:
    matchLabels:
      app: application
  strategy:
    type: RollingUpdate
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: application
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: application
        image: rubru94/tfm-springboot:0.0.7
        env:
        - name: SPRING_MYSQLDB_HOST
          value: mysqldb
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysqldb:3306/test?serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mailsecret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: tfm-springboot
  labels:
    app: application
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: application
  type: LoadBalancer


