name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build app without test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B clean package -DskipTests --file pom.xml 
      #run: mvn -B clean package -Dtest=ControllerUnitTest --file pom.xml 
  
  start_app:
    name: Docker-compose
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run docker-compose 
      run: docker-compose up

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [start_app]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Pass unit test
      run: mvn test -Dtest=ControllerUnitTest