name: Upload Release

on:
  release:
    types: [published]


jobs:
    docker-image:
      name: Build & push docker image
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build & push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rubru94/tfm-springboot
          tags: ${{ github.ref##*/ }}
